---
- hosts: localhost
  gather_facts: False
  vars_files:
  - ./anvil.yml
  vars:
    cloudname: AWS_S3
    cloudvendor: AMAZON_S3
    cloudbucket: mybucket
    cloudaccesskey: ''
    cloudsecretkey: ''
    cloudvolname: mybucket
    shared_volume: false
  tasks:
  - name: Add an Object Storage volume
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/object-storage-volumes"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: POST
      body: '{"name":"{{ cloudvolname }}","objectStoreLogicalVolume":{"_type":"OBJECT_STORE_LOGICAL_VOLUME","name":"{{ cloudbucket }}","node":{"_type":"NODE","name":"{{ cloudname }}"}},"_type":"OBJECT_STORAGE_VOLUME","node":{"_type":"NODE","name":"{{ cloudname }}"},"shared":"{{ shared_volume }}"}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
