---
# Generate instance report with display name, fault domain, and AZ mapping
# Usage: ansible-playbook -i inventory.oci.yml generate_instance_report.yml
#
# Output file: instance_report.csv (in current directory)

- name: Generate Instance Fault Domain and AZ Report
  hosts: all
  gather_facts: false

  vars:
    report_file: "{{ playbook_dir }}/instance_report.csv"

  tasks:
    - name: Convert fault domain to AZ
      ansible.builtin.set_fact:
        converted_az: "{{ oci_fault_domain | default('N/A') | regex_replace('FAULT-DOMAIN-', 'AZ') }}"

    - name: Build report data for this host
      ansible.builtin.set_fact:
        host_report_line: "{{ inventory_hostname }},{{ oci_fault_domain | default('N/A') }},{{ converted_az }}"

    - name: Write CSV header (run once)
      ansible.builtin.lineinfile:
        path: "{{ report_file }}"
        line: "display_name,fault_domain,az"
        create: true
        insertbefore: BOF
        mode: '0644'
      delegate_to: localhost
      run_once: true

    - name: Clear existing data (run once)
      ansible.builtin.shell: |
        if [ -f "{{ report_file }}" ]; then
          head -1 "{{ report_file }}" > "{{ report_file }}.tmp"
          mv "{{ report_file }}.tmp" "{{ report_file }}"
        fi
      delegate_to: localhost
      run_once: true
      changed_when: true

    - name: Append host data to report
      ansible.builtin.lineinfile:
        path: "{{ report_file }}"
        line: "{{ host_report_line }}"
        create: true
        mode: '0644'
      delegate_to: localhost

    - name: Display report location (run once)
      ansible.builtin.debug:
        msg: |
          Report generated: {{ report_file }}

          Preview:
          ----------------------------------------
          display_name,fault_domain,az
          {% for host in ansible_play_hosts %}
          {{ host }},{{ hostvars[host]['oci_fault_domain'] | default('N/A') }},{{ hostvars[host]['converted_az'] | default('N/A') }}
          {% endfor %}
          ----------------------------------------
      run_once: true
