---
# Preflight Check Playbook
# Compares cloud inventory with Hammerspace registered nodes
# Identifies new instances that need deployment
#
# Usage:
#   ansible-playbook preflight_check.yml -i inventory.aws.yml
#   ansible-playbook preflight_check.yml -i inventory.gcp.yml
#   ansible-playbook preflight_check.yml -i inventory.oci.yml
#
# Output:
#   - Report of registered vs new instances
#   - Limit string for targeting only new instances
#   - Optional: Write limit to file for scripting

- name: Gather inventory hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Collect inventory hostnames
      ansible.builtin.set_fact:
        inventory_host: "{{ inventory_hostname }}"
      delegate_to: localhost
      delegate_facts: false

- name: Preflight Check - Compare Inventory with Hammerspace
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yml
  vars:
    # Output file for limit string (optional)
    write_limit_file: true
    limit_file_path: "{{ playbook_dir }}/.new_instances_limit"

    # Output file for full report (optional)
    write_report_file: true
    report_file_path: "{{ playbook_dir }}/preflight_report.txt"

  tasks:
    # =========================================================================
    # Validate Configuration
    # =========================================================================
    - name: Validate Hammerspace API configuration
      ansible.builtin.assert:
        that:
          - hammerspace_api_host is defined
          - hammerspace_api_user is defined
          - hammerspace_api_password is defined
        fail_msg: |
          Hammerspace API configuration missing.
          Please set in vars/main.yml:
            hammerspace_api_host: "your-anvil-ip"
            hammerspace_api_user: "admin"
            hammerspace_api_password: "your-password"

    - name: Set API base URL
      ansible.builtin.set_fact:
        hs_api_url: "https://{{ hammerspace_api_host }}:8443/mgmt/v1.2/rest"

    # =========================================================================
    # Collect Inventory Hosts
    # =========================================================================
    - name: Get all inventory hosts
      ansible.builtin.set_fact:
        all_inventory_hosts: "{{ groups['all'] | default([]) }}"

    - name: Get storage_servers group hosts
      ansible.builtin.set_fact:
        storage_server_hosts: "{{ groups['storage_servers'] | default([]) }}"

    - name: Display inventory summary
      ansible.builtin.debug:
        msg: |
          Inventory Summary:
            Total hosts in inventory: {{ all_inventory_hosts | length }}
            Hosts in storage_servers group: {{ storage_server_hosts | length }}

    # =========================================================================
    # Query Hammerspace API for Registered Nodes
    # =========================================================================
    - name: Query Hammerspace for all registered nodes
      ansible.builtin.uri:
        url: "{{ hs_api_url }}/nodes"
        user: "{{ hammerspace_api_user }}"
        password: "{{ hammerspace_api_password }}"
        method: GET
        force_basic_auth: true
        status_code: 200
        validate_certs: "{{ hammerspace_api_validate_certs | default(false) }}"
        timeout: 60
      register: hs_nodes_response
      failed_when: false

    - name: Handle API connection failure
      ansible.builtin.fail:
        msg: |
          Failed to connect to Hammerspace API at {{ hammerspace_api_host }}
          Status: {{ hs_nodes_response.status | default('connection failed') }}
          Error: {{ hs_nodes_response.msg | default('Unknown error') }}

          Please verify:
            1. Hammerspace API host is correct: {{ hammerspace_api_host }}
            2. API credentials are valid
            3. Network connectivity to port 8443
      when: hs_nodes_response.status | default(0) != 200

    - name: Extract registered node names
      ansible.builtin.set_fact:
        hs_registered_nodes: "{{ hs_nodes_response.json | map(attribute='name') | list }}"
        hs_registered_nodes_details: "{{ hs_nodes_response.json }}"

    - name: Display Hammerspace nodes summary
      ansible.builtin.debug:
        msg: |
          Hammerspace Summary:
            Total registered nodes: {{ hs_registered_nodes | length }}

    # =========================================================================
    # Compare Inventory with Hammerspace
    # =========================================================================

    # Nodes in inventory but NOT in Hammerspace (new instances to deploy)
    - name: Identify new instances (in inventory, not in Hammerspace)
      ansible.builtin.set_fact:
        new_instances: "{{ storage_server_hosts | difference(hs_registered_nodes) }}"

    # Nodes in Hammerspace but NOT in inventory (orphaned or different inventory)
    - name: Identify orphaned nodes (in Hammerspace, not in inventory)
      ansible.builtin.set_fact:
        orphaned_nodes: "{{ hs_registered_nodes | intersect(storage_server_hosts) | difference(storage_server_hosts) }}"

    # Actually let's be more precise - nodes that match inventory naming pattern
    - name: Identify nodes in both (already registered)
      ansible.builtin.set_fact:
        already_registered: "{{ storage_server_hosts | intersect(hs_registered_nodes) }}"

    # Check for partial matches (inventory hostname might be part of HS node name)
    # e.g., "instance-001" in inventory might be "AZ1:instance-001" in Hammerspace
    - name: Check for AZ-prefixed matches in Hammerspace
      ansible.builtin.set_fact:
        az_prefixed_matches: >-
          {{
            storage_server_hosts | select('search', '^(?!' + (hs_registered_nodes | join('|')) + '$)') | list
            | select('in', hs_registered_nodes | map('regex_replace', '^AZ[0-9]+:', '') | list) | list
          }}
      ignore_errors: true

    - name: Build comprehensive match list
      ansible.builtin.set_fact:
        # Direct matches
        direct_matches: "{{ storage_server_hosts | intersect(hs_registered_nodes) }}"
        # Build list of inventory hosts that have AZ-prefixed versions in Hammerspace
        prefixed_in_hs: []

    - name: Check each inventory host for AZ-prefixed version in Hammerspace
      ansible.builtin.set_fact:
        prefixed_in_hs: "{{ prefixed_in_hs + [item] }}"
      loop: "{{ storage_server_hosts }}"
      when: >-
        item not in direct_matches and
        (hs_registered_nodes | select('match', '^AZ[0-9]+:' + item + '$') | list | length > 0)

    - name: Calculate final new instances list
      ansible.builtin.set_fact:
        final_new_instances: "{{ storage_server_hosts | difference(direct_matches) | difference(prefixed_in_hs) }}"
        final_registered: "{{ direct_matches + prefixed_in_hs }}"

    # =========================================================================
    # Generate Report
    # =========================================================================
    - name: Build preflight report
      ansible.builtin.set_fact:
        preflight_report: |
          ================================================================================
          PREFLIGHT CHECK REPORT
          ================================================================================
          Generated: {{ ansible_date_time.iso8601 | default(lookup('pipe', 'date -Iseconds')) }}
          Hammerspace API: {{ hammerspace_api_host }}

          SUMMARY
          --------------------------------------------------------------------------------
          Inventory hosts (storage_servers): {{ storage_server_hosts | length }}
          Hammerspace registered nodes:      {{ hs_registered_nodes | length }}
          Already registered:                {{ final_registered | length }}
          New instances to deploy:           {{ final_new_instances | length }}

          {% if final_registered | length > 0 %}
          ALREADY REGISTERED (will be skipped)
          --------------------------------------------------------------------------------
          {% for host in final_registered | sort %}
          - {{ host }}
          {% endfor %}
          {% endif %}

          {% if final_new_instances | length > 0 %}
          NEW INSTANCES (need deployment)
          --------------------------------------------------------------------------------
          {% for host in final_new_instances | sort %}
          - {{ host }}
          {% endfor %}
          {% endif %}

          {% if hs_registered_nodes | difference(storage_server_hosts) | difference(prefixed_in_hs | map('regex_replace', '^(.*)$', 'AZ[0-9]+:\\1') | list) | length > 0 %}
          HAMMERSPACE NODES NOT IN INVENTORY
          --------------------------------------------------------------------------------
          (These nodes exist in Hammerspace but are not in your current inventory)
          {% for node in hs_registered_nodes | sort %}
          {% if node not in storage_server_hosts %}
          - {{ node }}
          {% endif %}
          {% endfor %}
          {% endif %}

          ================================================================================
          RECOMMENDED COMMANDS
          ================================================================================
          {% if final_new_instances | length > 0 %}
          # Deploy to new instances only:
          ansible-playbook site.yml --limit "{{ final_new_instances | join(',') }}"

          # Dry run first (recommended):
          ansible-playbook site.yml --check --limit "{{ final_new_instances | join(',') }}"

          # Run precheck on new instances:
          ansible-playbook site.yml --tags precheck --limit "{{ final_new_instances | join(',') }}"
          {% else %}
          # All inventory hosts are already registered in Hammerspace.
          # No new deployments needed.

          # To re-run on all hosts anyway:
          ansible-playbook site.yml
          {% endif %}
          ================================================================================

    - name: Display preflight report
      ansible.builtin.debug:
        msg: "{{ preflight_report }}"

    # =========================================================================
    # Write Output Files
    # =========================================================================
    - name: Write limit file for new instances
      ansible.builtin.copy:
        content: "{{ final_new_instances | join(',') }}"
        dest: "{{ limit_file_path }}"
        mode: '0644'
      when:
        - write_limit_file | default(true)
        - final_new_instances | length > 0

    - name: Write empty limit file when no new instances
      ansible.builtin.copy:
        content: ""
        dest: "{{ limit_file_path }}"
        mode: '0644'
      when:
        - write_limit_file | default(true)
        - final_new_instances | length == 0

    - name: Write full report to file
      ansible.builtin.copy:
        content: "{{ preflight_report }}"
        dest: "{{ report_file_path }}"
        mode: '0644'
      when: write_report_file | default(true)

    # =========================================================================
    # Final Summary
    # =========================================================================
    - name: Display quick summary
      ansible.builtin.debug:
        msg: |

          ============================================
          PREFLIGHT CHECK COMPLETE
          ============================================
          New instances to deploy: {{ final_new_instances | length }}
          Already registered:      {{ final_registered | length }}

          {% if final_new_instances | length > 0 %}
          To deploy new instances, run:
            ansible-playbook site.yml --limit "{{ final_new_instances | join(',') }}"

          Or use the limit file:
            ansible-playbook site.yml --limit @{{ limit_file_path }}
          {% else %}
          All instances are already registered. No action needed.
          {% endif %}

          Full report saved to: {{ report_file_path }}
          ============================================

    # =========================================================================
    # Set Facts for Programmatic Use
    # =========================================================================
    - name: Set output facts for scripting
      ansible.builtin.set_fact:
        preflight_new_instances: "{{ final_new_instances }}"
        preflight_registered_instances: "{{ final_registered }}"
        preflight_limit_string: "{{ final_new_instances | join(',') }}"
        preflight_has_new_instances: "{{ final_new_instances | length > 0 }}"
