---
# Collect GPU memory fabric info from all instances
# Usage: ansible-playbook -i inventory.oci.yml collect_gpu_fabric.yml
#
# Output: gpu_fabric_data.txt (used by assign_az_to_volumes.py)

- name: Collect GPU Memory Fabric Data
  hosts: all
  gather_facts: false

  vars:
    output_file: "{{ playbook_dir }}/gpu_fabric_data.txt"

  tasks:
    - name: Get GPU memory fabric from instance metadata
      ansible.builtin.shell: |
        curl -sH "Authorization: Bearer Oracle" -L \
          http://169.254.169.254/opc/v2/host/rdmaTopologyData/customerGpuMemoryFabric 2>/dev/null || echo "N/A"
      register: gpu_fabric_result
      changed_when: false
      failed_when: false

    - name: Get private IP
      ansible.builtin.shell: |
        hostname -I | awk '{print $1}'
      register: private_ip_result
      changed_when: false

    - name: Set GPU fabric facts
      ansible.builtin.set_fact:
        gpu_fabric: "{{ gpu_fabric_result.stdout | trim }}"
        private_ip: "{{ private_ip_result.stdout | trim }}"

    - name: Ensure output file exists with header
      ansible.builtin.shell: |
        if [ ! -f "{{ output_file }}" ]; then
          echo "# GPU Fabric Data - Generated by collect_gpu_fabric.yml" > "{{ output_file }}"
          echo "# Format: gpu_fabric_ocid instance_name private_ip" >> "{{ output_file }}"
        fi
      delegate_to: localhost
      run_once: true
      changed_when: false

    - name: Check if host already exists in file
      ansible.builtin.shell: |
        grep -c "\\s{{ inventory_hostname }}\\s" "{{ output_file }}" 2>/dev/null || echo "0"
      register: host_exists
      delegate_to: localhost
      changed_when: false

    - name: Update existing entry (only if we have valid new data)
      when: gpu_fabric != 'N/A' and gpu_fabric | length > 0 and gpu_fabric.startswith('ocid1.')
      block:
        - name: Remove existing entry for this host
          ansible.builtin.lineinfile:
            path: "{{ output_file }}"
            regexp: ".*\\s{{ inventory_hostname }}\\s.*"
            state: absent
          delegate_to: localhost

        - name: Append new instance data to output file
          ansible.builtin.lineinfile:
            path: "{{ output_file }}"
            line: "{{ gpu_fabric }} {{ inventory_hostname }} {{ private_ip }}"
            mode: '0644'
          delegate_to: localhost

    - name: Skip update (keep existing record)
      ansible.builtin.debug:
        msg: "Keeping existing record for {{ inventory_hostname }} (no valid GPU fabric data received)"
      when: (gpu_fabric == 'N/A' or gpu_fabric | length == 0 or not gpu_fabric.startswith('ocid1.')) and host_exists.stdout | int > 0

    - name: Warn no GPU fabric found (new host)
      ansible.builtin.debug:
        msg: "WARNING: No GPU fabric data for {{ inventory_hostname }} (new host, not added to file)"
      when: (gpu_fabric == 'N/A' or gpu_fabric | length == 0 or not gpu_fabric.startswith('ocid1.')) and host_exists.stdout | int == 0

    - name: Display GPU fabric info
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: {{ gpu_fabric[-12:] if gpu_fabric != 'N/A' else 'N/A' }} ({{ private_ip }})"

- name: Generate Summary
  hosts: localhost
  gather_facts: false

  vars:
    output_file: "{{ playbook_dir }}/gpu_fabric_data.txt"

  tasks:
    - name: Read collected data
      ansible.builtin.shell: |
        grep -v '^#' {{ output_file }} | wc -l
      register: instance_count
      changed_when: false

    - name: Count unique GPU fabrics
      ansible.builtin.shell: |
        grep -v '^#' {{ output_file }} | awk '{print $1}' | sort -u | wc -l
      register: fabric_count
      changed_when: false

    - name: Display summary
      ansible.builtin.debug:
        msg: |
          ============================================
          GPU FABRIC DATA COLLECTED
          ============================================
          Output file: {{ output_file }}
          Instances: {{ instance_count.stdout | trim }}
          Unique GPU fabrics (AZs): {{ fabric_count.stdout | trim }}

          Next step - run assign_az_to_volumes.py:
            python3 assign_az_to_volumes.py \
              --host <ANVIL_IP> \
              --user admin \
              --password 'Hammer.123!!' \
              --gpu-fabric-file {{ output_file }} \
              --dry-run
          ============================================
